### ISSUE TITLE
Books list

### ISSUE THREAD

**Issue by Piciu19** [Piciu19/Librarian#41]
Utworzyć system spisu książek, który przechowuje informacje o tytule, ilości wypożyczonych i ilości książek w bibliotece z danego tytułu.
### Todo
- [x] Wyświetlanie spisu książek

|ID|Tytuł|Wypożyczone|Dostępne|
|--|--------|-----------------------|---------------|
|1|Światla Północy|1|2|

- [x] Menu wybierania książek przy dodawaniu wypożyczenia i zmiana ilości książek 
- [x] Zmiana ilości książek przy zakończeniu wypożyczenia
- [x] Możliwość zmiany książki w modyfikowaniu wypożyczenia
- [x] Dodawanie i usuwanie książek z listy (dla administratora)
