### ISSUE TITLE
Scan book QR code

### ISSUE THREAD

**Issue by Piciu19** [Piciu19/Librarian#43]
### Tasks

- [x] Skanowanie kodu QR przy dodawaniu wypożyczenia
- [ ] Skanowanie kodu QR przy modyfikowaniu wypożyczenia
- [x] Dodawanie, usuwanie i modyfikowanie książek
